//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abdikace
        ///abeceda
        ///adresa
        ///agrese
        ///akce
        ///aktovka
        ///alej
        ///alkohol
        ///amputace
        ///ananas
        ///andulka
        ///anekdota
        ///anketa
        ///antika
        ///anulovat
        ///archa
        ///arogance
        ///asfalt
        ///asistent
        ///aspirace
        ///astma
        ///astronom
        ///atlas
        ///atletika
        ///atol
        ///autobus
        ///azyl
        ///babka
        ///bachor
        ///bacil
        ///baculka
        ///badatel
        ///bageta
        ///bagr
        ///bahno
        ///bakterie
        ///balada
        ///baletka
        ///balkon
        ///balonek
        ///balvan
        ///balza
        ///bambus
        ///bankomat
        ///barbar
        ///baret
        ///barman
        ///baroko
        ///barva
        ///baterka
        ///batoh
        ///bavlna
        ///bazalka
        ///bazilika
        ///bazuka
        ///bedna
        ///beran
        ///beseda
        ///bestie
        ///beton
        ///bezinka
        ///bezmoc
        ///bez [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_cs {
            get {
                return ResourceManager.GetString("BIP-39.cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abandon
        ///ability
        ///able
        ///about
        ///above
        ///absent
        ///absorb
        ///abstract
        ///absurd
        ///abuse
        ///access
        ///accident
        ///account
        ///accuse
        ///achieve
        ///acid
        ///acoustic
        ///acquire
        ///across
        ///act
        ///action
        ///actor
        ///actress
        ///actual
        ///adapt
        ///add
        ///addict
        ///address
        ///adjust
        ///admit
        ///adult
        ///advance
        ///advice
        ///aerobic
        ///affair
        ///afford
        ///afraid
        ///again
        ///age
        ///agent
        ///agree
        ///ahead
        ///aim
        ///air
        ///airport
        ///aisle
        ///alarm
        ///album
        ///alcohol
        ///alert
        ///alien
        ///all
        ///alley
        ///allow
        ///almost
        ///alone
        ///alpha
        ///already
        ///also
        ///alter
        ///always
        ///amateur
        ///amazing
        ///among
        ///amount
        ///amused
        ///analyst
        ///a [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_en {
            get {
                return ResourceManager.GetString("BIP-39.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ábaco
        ///abdomen
        ///abeja
        ///abierto
        ///abogado
        ///abono
        ///aborto
        ///abrazo
        ///abrir
        ///abuelo
        ///abuso
        ///acabar
        ///academia
        ///acceso
        ///acción
        ///aceite
        ///acelga
        ///acento
        ///aceptar
        ///ácido
        ///aclarar
        ///acné
        ///acoger
        ///acoso
        ///activo
        ///acto
        ///actriz
        ///actuar
        ///acudir
        ///acuerdo
        ///acusar
        ///adicto
        ///admitir
        ///adoptar
        ///adorno
        ///aduana
        ///adulto
        ///aéreo
        ///afectar
        ///afición
        ///afinar
        ///afirmar
        ///ágil
        ///agitar
        ///agonía
        ///agosto
        ///agotar
        ///agregar
        ///agrio
        ///agua
        ///agudo
        ///águila
        ///aguja
        ///ahogo
        ///ahorro
        ///aire
        ///aislar
        ///ajedrez
        ///ajeno
        ///ajuste
        ///alacrán
        ///alambre
        ///alarma
        ///alba
        ///álbum
        ///alcalde
        ///aldea
        ///alegre
        ///alejar
        ///alerta
        ///aleta
        ///alfiler
        ///alga
        ///a [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_es {
            get {
                return ResourceManager.GetString("BIP-39.es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abaisser
        ///abandon
        ///abdiquer
        ///abeille
        ///abolir
        ///aborder
        ///aboutir
        ///aboyer
        ///abrasif
        ///abreuver
        ///abriter
        ///abroger
        ///abrupt
        ///absence
        ///absolu
        ///absurde
        ///abusif
        ///abyssal
        ///académie
        ///acajou
        ///acarien
        ///accabler
        ///accepter
        ///acclamer
        ///accolade
        ///accroche
        ///accuser
        ///acerbe
        ///achat
        ///acheter
        ///aciduler
        ///acier
        ///acompte
        ///acquérir
        ///acronyme
        ///acteur
        ///actif
        ///actuel
        ///adepte
        ///adéquat
        ///adhésif
        ///adjectif
        ///adjuger
        ///admettre
        ///admirer
        ///adopter
        ///adorer
        ///adoucir
        ///adresse
        ///adroit
        ///adulte
        ///adverbe
        ///aérer
        ///aéronef
        ///affaire
        ///affecter
        ///affiche
        ///affreux
        ///affubler
        ///agacer
        ///agencer
        ///agile
        ///agiter
        ///agrafer
        ///agr [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_fr {
            get {
                return ResourceManager.GetString("BIP-39.fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abaco
        ///abbaglio
        ///abbinato
        ///abete
        ///abisso
        ///abolire
        ///abrasivo
        ///abrogato
        ///accadere
        ///accenno
        ///accusato
        ///acetone
        ///achille
        ///acido
        ///acqua
        ///acre
        ///acrilico
        ///acrobata
        ///acuto
        ///adagio
        ///addebito
        ///addome
        ///adeguato
        ///aderire
        ///adipe
        ///adottare
        ///adulare
        ///affabile
        ///affetto
        ///affisso
        ///affranto
        ///aforisma
        ///afoso
        ///africano
        ///agave
        ///agente
        ///agevole
        ///aggancio
        ///agire
        ///agitare
        ///agonismo
        ///agricolo
        ///agrumeto
        ///aguzzo
        ///alabarda
        ///alato
        ///albatro
        ///alberato
        ///albo
        ///albume
        ///alce
        ///alcolico
        ///alettone
        ///alfa
        ///algebra
        ///aliante
        ///alibi
        ///alimento
        ///allagato
        ///allegro
        ///allievo
        ///allodola
        ///allusivo
        ///almeno
        ///alogeno
        ///alpaca [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_it {
            get {
                return ResourceManager.GetString("BIP-39.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a あいこくしん
        ///あいさつ
        ///あいだ
        ///あおぞら
        ///あかちゃん
        ///あきる
        ///あけがた
        ///あける
        ///あこがれる
        ///あさい
        ///あさひ
        ///あしあと
        ///あじわう
        ///あずかる
        ///あずき
        ///あそぶ
        ///あたえる
        ///あたためる
        ///あたりまえ
        ///あたる
        ///あつい
        ///あつかう
        ///あっしゅく
        ///あつまり
        ///あつめる
        ///あてな
        ///あてはまる
        ///あひる
        ///あぶら
        ///あぶる
        ///あふれる
        ///あまい
        ///あまど
        ///あまやかす
        ///あまり
        ///あみもの
        ///あめりか
        ///あやまる
        ///あゆむ
        ///あらいぐま
        ///あらし
        ///あらすじ
        ///あらためる
        ///あらゆる
        ///あらわす
        ///ありがとう
        ///あわせる
        ///あわてる
        ///あんい
        ///あんがい
        ///あんこ
        ///あんぜん
        ///あんてい
        ///あんない
        ///あんまり
        ///いいだす
        ///いおん
        ///いがい
        ///いがく
        ///いきおい
        ///いきなり
        ///いきもの
        ///いきる
        ///いくじ
        ///いくぶん
        ///いけばな
        ///いけん
        ///いこう
        ///いこく
        ///いこつ
        ///いさましい
        ///いさん
        ///いしき
        ///いじゅう
        ///いじょう
        ///いじわる
        ///いずみ
        ///いずれ
        ///いせい
        ///いせえび
        ///いせかい
        ///いせき
        ///いぜん
        ///いそうろう
        ///いそがしい
        ///いだい
        ///いだく
        ///いたずら
        ///いたみ
        ///いたりあ
        ///いちおう
        ///いちじ
        ///いちど
        ///いちば
        ///いちぶ
        ///いちりゅう
        ///いつか
        ///いっしゅん
        ///いっせい
        ///いっそう
        ///いっ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_ja {
            get {
                return ResourceManager.GetString("BIP-39.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 가격
        ///가끔
        ///가난
        ///가능
        ///가득
        ///가르침
        ///가뭄
        ///가방
        ///가상
        ///가슴
        ///가운데
        ///가을
        ///가이드
        ///가입
        ///가장
        ///가정
        ///가족
        ///가죽
        ///각오
        ///각자
        ///간격
        ///간부
        ///간섭
        ///간장
        ///간접
        ///간판
        ///갈등
        ///갈비
        ///갈색
        ///갈증
        ///감각
        ///감기
        ///감소
        ///감수성
        ///감자
        ///감정
        ///갑자기
        ///강남
        ///강당
        ///강도
        ///강력히
        ///강변
        ///강북
        ///강사
        ///강수량
        ///강아지
        ///강원도
        ///강의
        ///강제
        ///강조
        ///같이
        ///개구리
        ///개나리
        ///개방
        ///개별
        ///개선
        ///개성
        ///개인
        ///객관적
        ///거실
        ///거액
        ///거울
        ///거짓
        ///거품
        ///걱정
        ///건강
        ///건물
        ///건설
        ///건조
        ///건축
        ///걸음
        ///검사
        ///검토
        ///게시판
        ///게임
        ///겨울
        ///견해
        ///ᄀ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_ko {
            get {
                return ResourceManager.GetString("BIP-39.ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abacate
        ///abaixo
        ///abalar
        ///abater
        ///abduzir
        ///abelha
        ///aberto
        ///abismo
        ///abotoar
        ///abranger
        ///abreviar
        ///abrigar
        ///abrupto
        ///absinto
        ///absoluto
        ///absurdo
        ///abutre
        ///acabado
        ///acalmar
        ///acampar
        ///acanhar
        ///acaso
        ///aceitar
        ///acelerar
        ///acenar
        ///acervo
        ///acessar
        ///acetona
        ///achatar
        ///acidez
        ///acima
        ///acionado
        ///acirrar
        ///aclamar
        ///aclive
        ///acolhida
        ///acomodar
        ///acoplar
        ///acordar
        ///acumular
        ///acusador
        ///adaptar
        ///adega
        ///adentro
        ///adepto
        ///adequar
        ///aderente
        ///adesivo
        ///adeus
        ///adiante
        ///aditivo
        ///adjetivo
        ///adjunto
        ///admirar
        ///adorar
        ///adquirir
        ///adubo
        ///adverso
        ///advogado
        ///aeronave
        ///afastar
        ///aferir
        ///afetivo
        ///afinador
        ///afivelar
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_pt {
            get {
                return ResourceManager.GetString("BIP-39.pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 的
        ///一
        ///是
        ///在
        ///不
        ///了
        ///有
        ///和
        ///人
        ///这
        ///中
        ///大
        ///为
        ///上
        ///个
        ///国
        ///我
        ///以
        ///要
        ///他
        ///时
        ///来
        ///用
        ///们
        ///生
        ///到
        ///作
        ///地
        ///于
        ///出
        ///就
        ///分
        ///对
        ///成
        ///会
        ///可
        ///主
        ///发
        ///年
        ///动
        ///同
        ///工
        ///也
        ///能
        ///下
        ///过
        ///子
        ///说
        ///产
        ///种
        ///面
        ///而
        ///方
        ///后
        ///多
        ///定
        ///行
        ///学
        ///法
        ///所
        ///民
        ///得
        ///经
        ///十
        ///三
        ///之
        ///进
        ///着
        ///等
        ///部
        ///度
        ///家
        ///电
        ///力
        ///里
        ///如
        ///水
        ///化
        ///高
        ///自
        ///二
        ///理
        ///起
        ///小
        ///物
        ///现
        ///实
        ///加
        ///量
        ///都
        ///两
        ///体
        ///制
        ///机
        ///当
        ///使
        ///点
        ///从
        ///业
        ///本
        ///去
        ///把
        ///性
        ///好
        ///应
        ///开
        ///它
        ///合
        ///还
        ///因
        ///由
        ///其
        ///些
        ///然
        ///前
        ///外
        ///天
        ///政
        ///四
        ///日
        ///那
        ///社
        ///义
        ///事
        ///平
        ///形
        ///相
        ///全
        ///表
        ///间
        ///样
        ///与
        ///关
        ///各
        ///重
        ///新
        ///线
        ///内
        ///数
        ///正
        ///心
        ///反
        ///你
        ///明
        ///看
        ///原
        ///又
        ///么
        ///利
        ///比
        ///或
        ///但
        ///质
        ///气
        ///第
        ///向
        ///道
        ///命
        ///此
        ///变
        ///条
        ///只
        ///没
        ///结
        ///解
        ///问
        ///意
        ///建
        ///月
        ///公
        ///无
        ///系
        ///军
        ///很
        ///情
        ///者
        ///最
        ///立
        ///代
        ///想
        ///已
        ///通
        ///并
        ///提
        ///直
        ///题
        ///党
        ///程
        ///展
        ///五
        ///果
        ///料
        ///象
        ///员
        ///革
        ///位
        ///入
        ///常
        ///文
        ///总
        ///次
        ///品
        ///式
        ///活
        ///设
        ///及
        ///管
        ///特
        ///件
        ///长
        ///求
        ///老
        ///头
        ///基
        ///资
        ///边
        ///流
        ///路
        ///级
        ///少
        ///图
        ///山
        ///统
        ///接
        ///知
        ///较
        ///将
        ///组
        ///见
        ///计
        ///别
        ///她
        ///手
        ///角
        ///期
        ///根
        ///论
        ///运
        ///农
        ///指
        ///几
        ///九
        ///区
        ///强
        ///放
        ///决
        ///西
        ///被
        ///干
        ///做
        ///必
        ///战
        ///先
        ///回
        ///则
        ///任
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_zh {
            get {
                return ResourceManager.GetString("BIP-39.zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 的
        ///一
        ///是
        ///在
        ///不
        ///了
        ///有
        ///和
        ///人
        ///這
        ///中
        ///大
        ///為
        ///上
        ///個
        ///國
        ///我
        ///以
        ///要
        ///他
        ///時
        ///來
        ///用
        ///們
        ///生
        ///到
        ///作
        ///地
        ///於
        ///出
        ///就
        ///分
        ///對
        ///成
        ///會
        ///可
        ///主
        ///發
        ///年
        ///動
        ///同
        ///工
        ///也
        ///能
        ///下
        ///過
        ///子
        ///說
        ///產
        ///種
        ///面
        ///而
        ///方
        ///後
        ///多
        ///定
        ///行
        ///學
        ///法
        ///所
        ///民
        ///得
        ///經
        ///十
        ///三
        ///之
        ///進
        ///著
        ///等
        ///部
        ///度
        ///家
        ///電
        ///力
        ///裡
        ///如
        ///水
        ///化
        ///高
        ///自
        ///二
        ///理
        ///起
        ///小
        ///物
        ///現
        ///實
        ///加
        ///量
        ///都
        ///兩
        ///體
        ///制
        ///機
        ///當
        ///使
        ///點
        ///從
        ///業
        ///本
        ///去
        ///把
        ///性
        ///好
        ///應
        ///開
        ///它
        ///合
        ///還
        ///因
        ///由
        ///其
        ///些
        ///然
        ///前
        ///外
        ///天
        ///政
        ///四
        ///日
        ///那
        ///社
        ///義
        ///事
        ///平
        ///形
        ///相
        ///全
        ///表
        ///間
        ///樣
        ///與
        ///關
        ///各
        ///重
        ///新
        ///線
        ///內
        ///數
        ///正
        ///心
        ///反
        ///你
        ///明
        ///看
        ///原
        ///又
        ///麼
        ///利
        ///比
        ///或
        ///但
        ///質
        ///氣
        ///第
        ///向
        ///道
        ///命
        ///此
        ///變
        ///條
        ///只
        ///沒
        ///結
        ///解
        ///問
        ///意
        ///建
        ///月
        ///公
        ///無
        ///系
        ///軍
        ///很
        ///情
        ///者
        ///最
        ///立
        ///代
        ///想
        ///已
        ///通
        ///並
        ///提
        ///直
        ///題
        ///黨
        ///程
        ///展
        ///五
        ///果
        ///料
        ///象
        ///員
        ///革
        ///位
        ///入
        ///常
        ///文
        ///總
        ///次
        ///品
        ///式
        ///活
        ///設
        ///及
        ///管
        ///特
        ///件
        ///長
        ///求
        ///老
        ///頭
        ///基
        ///資
        ///邊
        ///流
        ///路
        ///級
        ///少
        ///圖
        ///山
        ///統
        ///接
        ///知
        ///較
        ///將
        ///組
        ///見
        ///計
        ///別
        ///她
        ///手
        ///角
        ///期
        ///根
        ///論
        ///運
        ///農
        ///指
        ///幾
        ///九
        ///區
        ///強
        ///放
        ///決
        ///西
        ///被
        ///幹
        ///做
        ///必
        ///戰
        ///先
        ///回
        ///則
        ///任
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BIP_39_zh_Hant {
            get {
                return ResourceManager.GetString("BIP-39.zh-Hant", resourceCulture);
            }
        }
    }
}
