global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "neo_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'neo-node'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['127.0.0.1:9101']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
