<?xml version="1.0" encoding="utf-8"?>
<Database Name="wt" Class="WalletDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Account" Member="Accounts" AccessModifier="Internal">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScriptHash" Type="System.Data.Linq.Binary" DbType="Binary(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RedeemScript" Type="System.Byte[]" DbType="VarBinary(547) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PrivateKeyEncrypted" Type="System.Byte[]" DbType="VarBinary(512) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.[Key]" Member="Keys">
    <Type Name="Key">
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Byte[]" DbType="Binary(32) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Unspent" Member="Unspents">
    <Type Name="Unspent">
      <Column Name="TxId" Type="System.Data.Linq.Binary" DbType="Binary(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Index" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AssetType" Type="System.Data.Linq.Binary" DbType="Binary(32) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Value" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ScriptHash" Type="System.Data.Linq.Binary" DbType="Binary(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Transaction" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="Hash" Type="System.Data.Linq.Binary" DbType="Binary(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="global::AntShares.Core.TransactionType" DbType="TinyInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RawData" Type="System.Byte[]" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>