// Copyright (C) 2016-2023 The Neo Project.
// 
// The neo-gui is free software distributed under the MIT software 
// license, see the accompanying file LICENSE in the main directory of
// the project or http://www.opensource.org/licenses/mit-license.php 
// for more details.
// 
// Redistribution and use in source and binary forms with or without
// modifications are permitted.

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO.
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add smart contract, corresponding private key missing in this wallet..
        /// </summary>
        internal static string AddContractFailedMessage {
            get {
                return ResourceManager.GetString("AddContractFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successful..
        /// </summary>
        internal static string ChangePasswordSuccessful {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be consumed, confirm?.
        /// </summary>
        internal static string CostTips {
            get {
                return ResourceManager.GetString("CostTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Warning.
        /// </summary>
        internal static string CostTitle {
            get {
                return ResourceManager.GetString("CostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string DeleteAddressConfirmationCaption {
            get {
                return ResourceManager.GetString("DeleteAddressConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon deletion, assets in these addresses will be permanently lost, are you sure to proceed?.
        /// </summary>
        internal static string DeleteAddressConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAddressConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets cannot be recovered once deleted, are you sure to delete the assets?.
        /// </summary>
        internal static string DeleteAssetConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAssetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter remark here, which will be recorded on the blockchain.
        /// </summary>
        internal static string EnterRemarkMessage {
            get {
                return ResourceManager.GetString("EnterRemarkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Remark.
        /// </summary>
        internal static string EnterRemarkTitle {
            get {
                return ResourceManager.GetString("EnterRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated in fault state..
        /// </summary>
        internal static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string ExpiredCertificate {
            get {
                return ResourceManager.GetString("ExpiredCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Priority Transaction.
        /// </summary>
        internal static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Watch-Only Address.
        /// </summary>
        internal static string ImportWatchOnlyAddress {
            get {
                return ResourceManager.GetString("ImportWatchOnlyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction initiated, but the signature is incomplete..
        /// </summary>
        internal static string IncompletedSignatureMessage {
            get {
                return ResourceManager.GetString("IncompletedSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete signature.
        /// </summary>
        internal static string IncompletedSignatureTitle {
            get {
                return ResourceManager.GetString("IncompletedSignatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the certificate installation..
        /// </summary>
        internal static string InstallCertificateCancel {
            get {
                return ResourceManager.GetString("InstallCertificateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the certificate.
        /// </summary>
        internal static string InstallCertificateCaption {
            get {
                return ResourceManager.GetString("InstallCertificateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO must install Onchain root certificate to validate assets on the blockchain, install it now?.
        /// </summary>
        internal static string InstallCertificateText {
            get {
                return ResourceManager.GetString("InstallCertificateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds, transaction cannot be initiated..
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Wallet.
        /// </summary>
        internal static string MigrateWalletCaption {
            get {
                return ResourceManager.GetString("MigrateWalletCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening wallet files in older versions, update to newest format?
        ///Note: updated files cannot be openned by clients in older versions!.
        /// </summary>
        internal static string MigrateWalletMessage {
            get {
                return ResourceManager.GetString("MigrateWalletMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet file relocated. New wallet file has been saved at: .
        /// </summary>
        internal static string MigrateWalletSucceedMessage {
            get {
                return ResourceManager.GetString("MigrateWalletSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Incorrect.
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data broadcast success, the hash is shown as follows:.
        /// </summary>
        internal static string RelaySuccessText {
            get {
                return ResourceManager.GetString("RelaySuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast Success.
        /// </summary>
        internal static string RelaySuccessTitle {
            get {
                return ResourceManager.GetString("RelaySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw:.
        /// </summary>
        internal static string RelayTitle {
            get {
                return ResourceManager.GetString("RelayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction sent, TXID:.
        /// </summary>
        internal static string SendTxSucceedMessage {
            get {
                return ResourceManager.GetString("SendTxSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successful.
        /// </summary>
        internal static string SendTxSucceedTitle {
            get {
                return ResourceManager.GetString("SendTxSucceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key that can sign the data is not found..
        /// </summary>
        internal static string SigningFailedKeyNotFoundMessage {
            get {
                return ResourceManager.GetString("SigningFailedKeyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input JSON object pending signature data..
        /// </summary>
        internal static string SigningFailedNoDataMessage {
            get {
                return ResourceManager.GetString("SigningFailedNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemIssuer {
            get {
                return ResourceManager.GetString("SystemIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, the counterparty falsified the transaction content!.
        /// </summary>
        internal static string TradeFailedFakeDataMessage {
            get {
                return ResourceManager.GetString("TradeFailedFakeDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, the counterparty generated illegal transaction content!.
        /// </summary>
        internal static string TradeFailedInvalidDataMessage {
            get {
                return ResourceManager.GetString("TradeFailedInvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, invalid transaction or unsynchronized blockchain, please try again when synchronized!.
        /// </summary>
        internal static string TradeFailedNoSyncMessage {
            get {
                return ResourceManager.GetString("TradeFailedNoSyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Signature.
        /// </summary>
        internal static string TradeNeedSignatureCaption {
            get {
                return ResourceManager.GetString("TradeNeedSignatureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction generated, please send the following information to the counterparty for signing:.
        /// </summary>
        internal static string TradeNeedSignatureMessage {
            get {
                return ResourceManager.GetString("TradeNeedSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Request.
        /// </summary>
        internal static string TradeRequestCreatedCaption {
            get {
                return ResourceManager.GetString("TradeRequestCreatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction request generated, please send it to the counterparty or merge it with the counterparty&apos;s request..
        /// </summary>
        internal static string TradeRequestCreatedMessage {
            get {
                return ResourceManager.GetString("TradeRequestCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Success.
        /// </summary>
        internal static string TradeSuccessCaption {
            get {
                return ResourceManager.GetString("TradeSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction sent, this is the TXID:.
        /// </summary>
        internal static string TradeSuccessMessage {
            get {
                return ResourceManager.GetString("TradeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unconfirmed.
        /// </summary>
        internal static string Unconfirmed {
            get {
                return ResourceManager.GetString("Unconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown issuer.
        /// </summary>
        internal static string UnknownIssuer {
            get {
                return ResourceManager.GetString("UnknownIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain unsynchronized, transaction cannot be sent..
        /// </summary>
        internal static string UnsynchronizedBlock {
            get {
                return ResourceManager.GetString("UnsynchronizedBlock", resourceCulture);
            }
        }
    }
}
